public with sharing class exampleCon {

    public PageReference incrementCounter() {
        return null;
    }


    public String getCount() {
        return null;
    }

String uname;

    public String getUsername() {
        return uname;
    }            
    public PageReference sayHello() {
        uname = UserInfo.getName();
        return null;
    }            
    public void setState(String n) {
        state = n;
    }            
    public String getState() {
        return state;
    }            
    public PageReference methodOne() {
        return null;
    }            
    private String state = 'no';
}